[package]
name = "neurotic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
env_logger = "0.11.5"
log = "0.4.22"
rand = "0.8.5"
ratatui = "0.29.0"
rayon = "1.10.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
